var hierarchy =
[
    [ "PokemonGame::BattleSystem", "class_pokemon_game_1_1_battle_system.html", null ],
    [ "PokemonGame::BurnTag", "struct_pokemon_game_1_1_burn_tag.html", null ],
    [ "PokemonGame::CombatantsComponent", "struct_pokemon_game_1_1_combatants_component.html", null ],
    [ "PokemonGame::ControllerComponent", "struct_pokemon_game_1_1_controller_component.html", null ],
    [ "bagel::ent_type", "structbagel_1_1ent__type.html", null ],
    [ "PokemonGame::ent_type", "struct_pokemon_game_1_1ent__type.html", null ],
    [ "bagel::Entity", "classbagel_1_1_entity.html", null ],
    [ "PokemonGame::HealthComponent", "struct_pokemon_game_1_1_health_component.html", null ],
    [ "PokemonGame::IdentityComponent", "struct_pokemon_game_1_1_identity_component.html", null ],
    [ "bagel::Mask", "classbagel_1_1_mask.html", null ],
    [ "bagel::MaskBuilder", "classbagel_1_1_mask_builder.html", null ],
    [ "PokemonGame::MovesetComponent", "struct_pokemon_game_1_1_moveset_component.html", null ],
    [ "PokemonGame::MoveStats", "struct_pokemon_game_1_1_move_stats.html", null ],
    [ "bagel::NoCopy", "structbagel_1_1_no_copy.html", [
      [ "bagel::DynamicBag< T, N >", "classbagel_1_1_dynamic_bag.html", null ]
    ] ],
    [ "bagel::NoInstance", "structbagel_1_1_no_instance.html", [
      [ "bagel::PackedStorage< PokemonGame::MovesetComponent >", "classbagel_1_1_packed_storage.html", null ],
      [ "bagel::PackedStorage< PokemonGame::CombatantsComponent >", "classbagel_1_1_packed_storage.html", null ],
      [ "bagel::PackedStorage< PokemonGame::StatusEffectComponent >", "classbagel_1_1_packed_storage.html", null ],
      [ "bagel::SparseStorage< PokemonGame::IdentityComponent >", "classbagel_1_1_sparse_storage.html", null ],
      [ "bagel::SparseStorage< PokemonGame::HealthComponent >", "classbagel_1_1_sparse_storage.html", null ],
      [ "bagel::SparseStorage< PokemonGame::StatsComponent >", "classbagel_1_1_sparse_storage.html", null ],
      [ "bagel::SparseStorage< PokemonGame::PartyComponent >", "classbagel_1_1_sparse_storage.html", null ],
      [ "bagel::Storage< PokemonGame::BurnTag >", "structbagel_1_1_storage_3_01_pokemon_game_1_1_burn_tag_01_4.html", null ],
      [ "bagel::Storage< PokemonGame::CombatantsComponent >", "structbagel_1_1_storage_3_01_pokemon_game_1_1_combatants_component_01_4.html", null ],
      [ "bagel::Storage< PokemonGame::HealthComponent >", "structbagel_1_1_storage_3_01_pokemon_game_1_1_health_component_01_4.html", null ],
      [ "bagel::Storage< PokemonGame::IdentityComponent >", "structbagel_1_1_storage_3_01_pokemon_game_1_1_identity_component_01_4.html", null ],
      [ "bagel::Storage< PokemonGame::MovesetComponent >", "structbagel_1_1_storage_3_01_pokemon_game_1_1_moveset_component_01_4.html", null ],
      [ "bagel::Storage< PokemonGame::ParalyzeTag >", "structbagel_1_1_storage_3_01_pokemon_game_1_1_paralyze_tag_01_4.html", null ],
      [ "bagel::Storage< PokemonGame::PartyComponent >", "structbagel_1_1_storage_3_01_pokemon_game_1_1_party_component_01_4.html", null ],
      [ "bagel::Storage< PokemonGame::PoisonTag >", "structbagel_1_1_storage_3_01_pokemon_game_1_1_poison_tag_01_4.html", null ],
      [ "bagel::Storage< PokemonGame::StatsComponent >", "structbagel_1_1_storage_3_01_pokemon_game_1_1_stats_component_01_4.html", null ],
      [ "bagel::Storage< PokemonGame::StatusEffectComponent >", "structbagel_1_1_storage_3_01_pokemon_game_1_1_status_effect_component_01_4.html", null ],
      [ "bagel::TaggedStorage< PokemonGame::PoisonTag >", "classbagel_1_1_tagged_storage.html", null ],
      [ "bagel::TaggedStorage< PokemonGame::BurnTag >", "classbagel_1_1_tagged_storage.html", null ],
      [ "bagel::TaggedStorage< PokemonGame::ParalyzeTag >", "classbagel_1_1_tagged_storage.html", null ],
      [ "bagel::Component< class >", "structbagel_1_1_component.html", null ],
      [ "bagel::PackedStorage< T >", "classbagel_1_1_packed_storage.html", null ],
      [ "bagel::SparseStorage< T >", "classbagel_1_1_sparse_storage.html", null ],
      [ "bagel::StackStorage< T >", "classbagel_1_1_stack_storage.html", null ],
      [ "bagel::Storage< T >", "structbagel_1_1_storage.html", null ],
      [ "bagel::Storage< PokemonGame::BurnTag >", "structbagel_1_1_storage_3_01_pokemon_game_1_1_burn_tag_01_4.html", null ],
      [ "bagel::Storage< PokemonGame::CombatantsComponent >", "structbagel_1_1_storage_3_01_pokemon_game_1_1_combatants_component_01_4.html", null ],
      [ "bagel::Storage< PokemonGame::HealthComponent >", "structbagel_1_1_storage_3_01_pokemon_game_1_1_health_component_01_4.html", null ],
      [ "bagel::Storage< PokemonGame::IdentityComponent >", "structbagel_1_1_storage_3_01_pokemon_game_1_1_identity_component_01_4.html", null ],
      [ "bagel::Storage< PokemonGame::MovesetComponent >", "structbagel_1_1_storage_3_01_pokemon_game_1_1_moveset_component_01_4.html", null ],
      [ "bagel::Storage< PokemonGame::ParalyzeTag >", "structbagel_1_1_storage_3_01_pokemon_game_1_1_paralyze_tag_01_4.html", null ],
      [ "bagel::Storage< PokemonGame::PartyComponent >", "structbagel_1_1_storage_3_01_pokemon_game_1_1_party_component_01_4.html", null ],
      [ "bagel::Storage< PokemonGame::PoisonTag >", "structbagel_1_1_storage_3_01_pokemon_game_1_1_poison_tag_01_4.html", null ],
      [ "bagel::Storage< PokemonGame::StatsComponent >", "structbagel_1_1_storage_3_01_pokemon_game_1_1_stats_component_01_4.html", null ],
      [ "bagel::Storage< PokemonGame::StatusEffectComponent >", "structbagel_1_1_storage_3_01_pokemon_game_1_1_status_effect_component_01_4.html", null ],
      [ "bagel::TaggedStorage< T >", "classbagel_1_1_tagged_storage.html", null ],
      [ "bagel::World", "classbagel_1_1_world.html", null ]
    ] ],
    [ "PokemonGame::ParalyzeTag", "struct_pokemon_game_1_1_paralyze_tag.html", null ],
    [ "PokemonGame::PartyComponent", "struct_pokemon_game_1_1_party_component.html", null ],
    [ "PokemonGame::PoisonTag", "struct_pokemon_game_1_1_poison_tag.html", null ],
    [ "bagel::Register&lt; T &gt;", "structbagel_1_1_register.html", null ],
    [ "bagel::StaticBag&lt; T, N &gt;", "classbagel_1_1_static_bag.html", null ],
    [ "PokemonGame::StatsComponent", "struct_pokemon_game_1_1_stats_component.html", null ],
    [ "PokemonGame::StatusEffectComponent", "struct_pokemon_game_1_1_status_effect_component.html", null ]
];